USE [master]
GO

/****** Object:  Database [cuidaDB]    Script Date: 09/06/2019 08:57:48 ******/
CREATE DATABASE [cuidaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'cuidaDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\cuidaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'cuidaDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\cuidaDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [cuidaDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [cuidaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [cuidaDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [cuidaDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [cuidaDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [cuidaDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [cuidaDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [cuidaDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [cuidaDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [cuidaDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [cuidaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [cuidaDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [cuidaDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [cuidaDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [cuidaDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [cuidaDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [cuidaDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [cuidaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [cuidaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [cuidaDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [cuidaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [cuidaDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [cuidaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [cuidaDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [cuidaDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [cuidaDB] SET  MULTI_USER 
GO

ALTER DATABASE [cuidaDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [cuidaDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [cuidaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [cuidaDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [cuidaDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [cuidaDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [cuidaDB] SET  READ_WRITE 
GO


