//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThanosSoft.Infraestrutura.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDocumento
    {
        public int codTipoDocumento { get; set; }
        public string nome { get; set; }
        public bool ativo { get; set; }
    }
}
