//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThanosSoft.Infraestrutura.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.UsuariosDocumentos = new HashSet<UsuarioDocumento>();
        }
    
        public int codUsuario { get; set; }
        public string nome { get; set; }
        public string sobrenome { get; set; }
        public string rg { get; set; }
        public string cpf { get; set; }
        public string cnh { get; set; }
        public string tipocnh { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
        public string sexo { get; set; }
        public string estadoCivil { get; set; }
        public string nomePai { get; set; }
        public string nomeMae { get; set; }
        public string cartaoCidadao { get; set; }
        public string cartaoSus { get; set; }
        public string carteiraTrabalhoNumero { get; set; }
        public string certidaoNascimento { get; set; }
        public string certidaoCasamento { get; set; }
        public string conjuge { get; set; }
        public string cpfConjuge { get; set; }
        public string rgConjuge { get; set; }
        public string senha { get; set; }
        public Nullable<int> tipoCadastro { get; set; }
        public Nullable<System.DateTime> dataCadastro { get; set; }
        public Nullable<System.DateTime> dataUltimaAtualizacao { get; set; }
        public bool ativo { get; set; }
        public string endereco { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioDocumento> UsuariosDocumentos { get; set; }
    }
}
