//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThanosSoft.Infraestrutura.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioDocumento
    {
        public int codUsuario { get; set; }
        public int codTipoDocumento { get; set; }
        public byte[] arquivo { get; set; }
        public string tipoArquivo { get; set; }
    
        public virtual TipoDocumento TiposDocumentos { get; set; }
    }
}
